global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: https://magda-dev.terria.io
  rollingUpdate:
    maxUnavailable: 1
  image:
    tag: "0.0.41-0"

tags:
  all: true
  sleuther-broken-link: true
  sleuther-linked-data-rating: true
  sleuther-visualization: true
  sleuther-format: true

gateway:
  loadBalancerIP: "104.199.180.124"
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
combined-db:
  resources:
    requests:
      cpu: 400m
      memory: 1500Mi
    limits:
      cpu: 1500m
  waleBackup:
    method: WAL
    gsPrefix: "gs://magda-postgres-backups-asia/dev"
    executionTime: 03:00
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: TerriaJS-5e042b649f8a.json
  data:
    storage: 250Gi
elasticsearch:
  data:
    heapSize: 500m
    pluginsInstall: "repository-gcs"
    resources:
      requests:
        cpu: 400m
        memory: 1000Mi
  backup:
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: db-service-account-private-key.json
feedback-api:
  gitHubIssuesUrl: "https://api.github.com/repos/TerriaJS/Magda-Feedback/issues"
indexer:
  resources:
    requests:
      cpu: 100m
      memory: 0
  readSnapshots: true
  makeSnapshots: true
  elasticsearch:
    useGcsSnapshots: true
    gcsSnapshotBucket: "magda-es-snapshots-dev"
    gcsSnapshotClient: "default"
preview-map:
  resources:
    requests:
      cpu: 100m
      memory: 0
registry-api:
  resources:
    requests:
      cpu: 250m
      memory: 0
search-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
web-server:
  cspReportUri: https://sdga.report-uri.com/r/d/csp/enforce
  resources:
    requests:
      cpu: 100m
      memory: 0
sleuther-linked-data-rating:
  resources:
    requests:
      cpu: 100m
      memory: 0
sleuther-broken-link:
  resources:
    requests:
      cpu: 100m
      memory: 0
    limits:
      cpu: 500m
sleuther-visualization:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
sleuther-format:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 500m
admin-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
authorization-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
discussions-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
correspondence-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
  defaultRecipient: "magda-test@googlegroups.com"
  smtpHostname: "smtp.mailgun.org"
  smtpPort: 2525