global:
  rollingUpdate:
    maxUnavailable: 1000
  image:
    imagePullSecret: "regcred"
  exposeNodePorts: false

tags:
  all: true
  dev-ingress: true

gateway:
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
  autoscaler:
    enabled: false
  service:
    type: ClusterIP
combined-db:
  resources:
    requests:
      cpu: 400m
      memory: 1500Mi
    limits:
      cpu: 1500m
  waleBackup:
    method: WAL
    readOnly: "TRUE"
    recoveryMode: "immediate"
    gsPrefix: "gs://magda-postgres-backups-asia/dev"
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: db-service-account-private-key.json
  data:
    storage: 250Gi
elasticsearch:
  data:
    heapSize: 500m
    pluginsInstall: "repository-gcs"
    resources:
      requests:
        cpu: 400m
        memory: 1000Mi
  backup:
    googleApplicationCreds:
      secretName: storage-account-credentials
      fileName: db-service-account-private-key.json
indexer:
  resources:
    requests:
      cpu: 100m
      memory: 0
  readSnapshots: true
  makeSnapshots: false
  elasticsearch:
    useGcsSnapshots: true
    gcsSnapshotBucket: "magda-es-snapshots-dev"
    gcsSnapshotClient: "default"
preview-map:
  resources:
    requests:
      cpu: 100m
      memory: 0
registry-api:
  resources:
    requests:
      cpu: 250m
      memory: 0
search-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
web-server:
  resources:
    requests:
      cpu: 100m
      memory: 0
sleuther-linked-data-rating:
  resources:
    requests:
      cpu: 100m
      memory: 0
sleuther-broken-link:
  resources:
    requests:
      cpu: 100m
      memory: 0
    limits:
      cpu: 500m
sleuther-visualization:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
sleuther-format:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 500m
admin-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
authorization-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
discussions-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
correspondence-api:
  resources:
    requests:
      cpu: 100m
      memory: 0
  defaultRecipient: "magda-test@googlegroups.com"
  smtpHostname: "smtp.mailgun.org"
  smtpPort: 2525